// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Fv1.0.0

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_plantmilkmode;
extern lv_obj_t * ui_cleanmode;
extern lv_obj_t * ui_toufumode;
extern lv_obj_t * ui_TimeLable2;
extern lv_obj_t * ui_TimerFunction2;
extern lv_obj_t * ui_Locked2;
extern lv_obj_t * ui_Level_2;
extern lv_obj_t * ui_WiFi2;
extern lv_obj_t * ui_Bluetooth2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

