// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Fv1.0.0

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_plantmilkmode = NULL;
lv_obj_t * ui_cleanmode = NULL;
lv_obj_t * ui_toufumode = NULL;
lv_obj_t * ui_TimeLable2 = NULL;
lv_obj_t * ui_TimerFunction2 = NULL;
lv_obj_t * ui_Locked2 = NULL;
lv_obj_t * ui_Level_2 = NULL;
lv_obj_t * ui_WiFi2 = NULL;
lv_obj_t * ui_Bluetooth2 = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image4, &ui_img_titilestate_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 85
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 444
    lv_obj_set_x(ui_Image4, 20);
    lv_obj_set_y(ui_Image4, 20);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plantmilkmode = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_plantmilkmode, &ui_img_modeplantmilk_png);
    lv_obj_set_width(ui_plantmilkmode, LV_SIZE_CONTENT);   /// 205
    lv_obj_set_height(ui_plantmilkmode, LV_SIZE_CONTENT);    /// 440
    lv_obj_set_x(ui_plantmilkmode, 115);
    lv_obj_set_y(ui_plantmilkmode, 20);
    lv_obj_add_flag(ui_plantmilkmode, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_plantmilkmode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cleanmode = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_cleanmode, &ui_img_menuclean_png);
    lv_obj_set_width(ui_cleanmode, LV_SIZE_CONTENT);   /// 205
    lv_obj_set_height(ui_cleanmode, LV_SIZE_CONTENT);    /// 440
    lv_obj_set_x(ui_cleanmode, 115);
    lv_obj_set_y(ui_cleanmode, 20);
    lv_obj_add_flag(ui_cleanmode, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cleanmode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_toufumode = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_toufumode, &ui_img_menutoufu_png);
    lv_obj_set_width(ui_toufumode, LV_SIZE_CONTENT);   /// 205
    lv_obj_set_height(ui_toufumode, LV_SIZE_CONTENT);    /// 440
    lv_obj_set_x(ui_toufumode, 115);
    lv_obj_set_y(ui_toufumode, 20);
    lv_obj_add_flag(ui_toufumode, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_toufumode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimeLable2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_TimeLable2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLable2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLable2, -65);
    lv_obj_set_y(ui_TimeLable2, 235);
    lv_obj_set_align(ui_TimeLable2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLable2, "10:30 AM");
    lv_obj_set_style_transform_pivot_x(ui_TimeLable2, lv_obj_get_width(ui_TimeLable2) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_TimeLable2, lv_obj_get_height(ui_TimeLable2) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_TimeLable2, 2700, LV_PART_MAIN);

    ui_TimerFunction2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_TimerFunction2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimerFunction2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimerFunction2, -65);
    lv_obj_set_y(ui_TimerFunction2, 155);
    lv_obj_set_align(ui_TimerFunction2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimerFunction2, "00:45:00");
    lv_obj_set_style_transform_pivot_x(ui_TimerFunction2, lv_obj_get_width(ui_TimerFunction2) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_TimerFunction2, lv_obj_get_height(ui_TimerFunction2) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_TimerFunction2, 2700, LV_PART_MAIN);

    ui_Locked2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Locked2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Locked2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Locked2, -68);
    lv_obj_set_y(ui_Locked2, 75);
    lv_obj_set_align(ui_Locked2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Locked2, "Locked");
    lv_obj_set_style_transform_pivot_x(ui_Locked2, lv_obj_get_width(ui_Locked2) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_Locked2, lv_obj_get_height(ui_Locked2) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_Locked2, 2700, LV_PART_MAIN);

    ui_Level_2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Level_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Level_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Level_2, -60);
    lv_obj_set_y(ui_Level_2, 2);
    lv_obj_set_align(ui_Level_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Level_2, "Level 70%");
    lv_obj_set_style_transform_pivot_x(ui_Level_2, lv_obj_get_width(ui_Level_2) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_Level_2, lv_obj_get_height(ui_Level_2) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_Level_2, 2700, LV_PART_MAIN);

    ui_WiFi2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_WiFi2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFi2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFi2, -80);
    lv_obj_set_y(ui_WiFi2, -90);
    lv_obj_set_align(ui_WiFi2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFi2, "WiFi");
    lv_obj_set_style_transform_pivot_x(ui_WiFi2, lv_obj_get_width(ui_WiFi2) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_WiFi2, lv_obj_get_height(ui_WiFi2) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_WiFi2, 2700, LV_PART_MAIN);

    ui_Bluetooth2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Bluetooth2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Bluetooth2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Bluetooth2, -60);
    lv_obj_set_y(ui_Bluetooth2, -150);
    lv_obj_set_align(ui_Bluetooth2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Bluetooth2, "Bluetooth");
    lv_obj_set_style_transform_pivot_x(ui_Bluetooth2, lv_obj_get_width(ui_Bluetooth2) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_Bluetooth2, lv_obj_get_height(ui_Bluetooth2) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_Bluetooth2, 2700, LV_PART_MAIN);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Image4 = NULL;
    ui_plantmilkmode = NULL;
    ui_cleanmode = NULL;
    ui_toufumode = NULL;
    ui_TimeLable2 = NULL;
    ui_TimerFunction2 = NULL;
    ui_Locked2 = NULL;
    ui_Level_2 = NULL;
    ui_WiFi2 = NULL;
    ui_Bluetooth2 = NULL;

}
