// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Fv1.0.0

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_TimeLable4;
extern lv_obj_t * ui_TimerFunction4;
extern lv_obj_t * ui_Locked4;
extern lv_obj_t * ui_Level_4;
extern lv_obj_t * ui_WiFi4;
extern lv_obj_t * ui_Bluetooth4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

