// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Fv1.0.0

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_defaultpage = NULL;
lv_obj_t * ui_TimeLable = NULL;
lv_obj_t * ui_TimerFunction = NULL;
lv_obj_t * ui_Locked = NULL;
lv_obj_t * ui_Level_70 = NULL;
lv_obj_t * ui_WiFi = NULL;
lv_obj_t * ui_Bluetooth = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image2, &ui_img_titilestate_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 85
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 444
    lv_obj_set_x(ui_Image2, 20);
    lv_obj_set_y(ui_Image2, 20);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_defaultpage = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_defaultpage, &ui_img_homepage_png);
    lv_obj_set_width(ui_defaultpage, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_defaultpage, LV_SIZE_CONTENT);    /// 424
    lv_obj_set_x(ui_defaultpage, 133);
    lv_obj_set_y(ui_defaultpage, 36);
    lv_obj_add_flag(ui_defaultpage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_defaultpage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimeLable = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_TimeLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLable, -65);
    lv_obj_set_y(ui_TimeLable, 235);
    lv_obj_set_align(ui_TimeLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLable, "10:30 AM");
    lv_obj_set_style_transform_pivot_x(ui_TimeLable, lv_obj_get_width(ui_TimeLable) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_TimeLable, lv_obj_get_height(ui_TimeLable) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_TimeLable, 2700, LV_PART_MAIN);

    ui_TimerFunction = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_TimerFunction, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimerFunction, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimerFunction, -65);
    lv_obj_set_y(ui_TimerFunction, 155);
    lv_obj_set_align(ui_TimerFunction, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimerFunction, "00:45:00");
    lv_obj_set_style_transform_pivot_x(ui_TimerFunction, lv_obj_get_width(ui_TimerFunction) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_TimerFunction, lv_obj_get_height(ui_TimerFunction) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_TimerFunction, 2700, LV_PART_MAIN);  

    ui_Locked = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Locked, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Locked, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Locked, -68);
    lv_obj_set_y(ui_Locked, 75);
    lv_obj_set_align(ui_Locked, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Locked, "Locked");
    lv_obj_set_style_transform_pivot_x(ui_Locked, lv_obj_get_width(ui_Locked) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_Locked, lv_obj_get_height(ui_Locked) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_Locked, 2700, LV_PART_MAIN);

    ui_Level_70 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Level_70, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Level_70, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Level_70, -60);
    lv_obj_set_y(ui_Level_70, 2);
    lv_obj_set_align(ui_Level_70, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Level_70, "Level 70%");
    lv_obj_set_style_transform_pivot_x(ui_Level_70, lv_obj_get_width(ui_Level_70) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_Level_70, lv_obj_get_height(ui_Level_70) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_Level_70, 2700, LV_PART_MAIN);

    ui_WiFi = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_WiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFi, -80);
    lv_obj_set_y(ui_WiFi, -90);
    lv_obj_set_align(ui_WiFi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFi, "WiFi");
    lv_obj_set_style_transform_pivot_x(ui_WiFi, lv_obj_get_width(ui_WiFi) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_WiFi, lv_obj_get_height(ui_WiFi) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_WiFi, 2700, LV_PART_MAIN);

    ui_Bluetooth = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Bluetooth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Bluetooth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Bluetooth, -60);
    lv_obj_set_y(ui_Bluetooth, -150);
    lv_obj_set_align(ui_Bluetooth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Bluetooth, "Bluetooth");
    lv_obj_set_style_transform_pivot_x(ui_Bluetooth, lv_obj_get_width(ui_Bluetooth) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_Bluetooth, lv_obj_get_height(ui_Bluetooth) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_Bluetooth, 2700, LV_PART_MAIN);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Image2 = NULL;
    ui_defaultpage = NULL;
    ui_TimeLable = NULL;
    ui_TimerFunction = NULL;
    ui_Locked = NULL;
    ui_Level_70 = NULL;
    ui_WiFi = NULL;
    ui_Bluetooth = NULL;

}
