// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Fv1.0.0

#include "../ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Image19 = NULL;
lv_obj_t * ui_Image26 = NULL;
lv_obj_t * ui_TimeLable3 = NULL;
lv_obj_t * ui_TimerFunction3 = NULL;
lv_obj_t * ui_Locked3 = NULL;
lv_obj_t * ui_Level_3 = NULL;
lv_obj_t * ui_WiFi3 = NULL;
lv_obj_t * ui_Bluetooth3 = NULL;
// event funtions

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image10, &ui_img_titilestate_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 85
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 444
    lv_obj_set_x(ui_Image10, 20);
    lv_obj_set_y(ui_Image10, 20);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image11, &ui_img_process_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 23
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 169
    lv_obj_set_x(ui_Image11, 125);
    lv_obj_set_y(ui_Image11, -20);
    lv_obj_set_align(ui_Image11, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image12, &ui_img_line_4_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 440
    lv_obj_set_x(ui_Image12, 179);
    lv_obj_set_y(ui_Image12, 20);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image13, &ui_img_plantmilk_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 440
    lv_obj_set_x(ui_Image13, 199);
    lv_obj_set_y(ui_Image13, 20);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image19 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image19, &ui_img_tofu_png);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 440
    lv_obj_set_x(ui_Image19, 199);
    lv_obj_set_y(ui_Image19, 20);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image26 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image26, &ui_img_493133332);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 440
    lv_obj_set_x(ui_Image26, 199);
    lv_obj_set_y(ui_Image26, 20);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimeLable3 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_TimeLable3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLable3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLable3, -65);
    lv_obj_set_y(ui_TimeLable3, 235);
    lv_obj_set_align(ui_TimeLable3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLable3, "10:30 AM");
    lv_obj_set_style_transform_pivot_x(ui_TimeLable3, lv_obj_get_width(ui_TimeLable3) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_TimeLable3, lv_obj_get_height(ui_TimeLable3) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_TimeLable3, 2700, LV_PART_MAIN);
    

    ui_TimerFunction3 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_TimerFunction3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimerFunction3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimerFunction3, -65);
    lv_obj_set_y(ui_TimerFunction3, 155);
    lv_obj_set_align(ui_TimerFunction3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimerFunction3, "00:45:00");
    lv_obj_set_style_transform_pivot_x(ui_TimerFunction3, lv_obj_get_width(ui_TimerFunction3) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_TimerFunction3, lv_obj_get_height(ui_TimerFunction3) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_TimerFunction3, 2700, LV_PART_MAIN);

    ui_Locked3 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Locked3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Locked3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Locked3, -68);
    lv_obj_set_y(ui_Locked3, 75);
    lv_obj_set_align(ui_Locked3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Locked3, "Locked");
    lv_obj_set_style_transform_pivot_x(ui_Locked3, lv_obj_get_width(ui_Locked3) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_Locked3, lv_obj_get_height(ui_Locked3) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_Locked3, 2700, LV_PART_MAIN);

    ui_Level_3 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Level_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Level_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Level_3, -60);
    lv_obj_set_y(ui_Level_3, 2);
    lv_obj_set_align(ui_Level_3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Level_3, "Level 70%");
    lv_obj_set_style_transform_pivot_x(ui_Level_3, lv_obj_get_width(ui_Level_3) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_Level_3, lv_obj_get_height(ui_Level_3) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_Level_3, 2700, LV_PART_MAIN);

    ui_WiFi3 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_WiFi3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFi3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFi3, -80);
    lv_obj_set_y(ui_WiFi3, -90);
    lv_obj_set_align(ui_WiFi3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFi3, "WiFi");
    lv_obj_set_style_transform_pivot_x(ui_WiFi3, lv_obj_get_width(ui_WiFi3) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_WiFi3, lv_obj_get_height(ui_WiFi3) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_WiFi3, 2700, LV_PART_MAIN);

    ui_Bluetooth3 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Bluetooth3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Bluetooth3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Bluetooth3, -60);
    lv_obj_set_y(ui_Bluetooth3, -150);
    lv_obj_set_align(ui_Bluetooth3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Bluetooth3, "Bluetooth");
    lv_obj_set_style_transform_pivot_x(ui_Bluetooth3, lv_obj_get_width(ui_Bluetooth3) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_Bluetooth3, lv_obj_get_height(ui_Bluetooth3) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_Bluetooth3, 2700, LV_PART_MAIN);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Image10 = NULL;
    ui_Image11 = NULL;
    ui_Image12 = NULL;
    ui_Image13 = NULL;
    ui_Image19 = NULL;
    ui_Image26 = NULL;
    ui_TimeLable3 = NULL;
    ui_TimerFunction3 = NULL;
    ui_Locked3 = NULL;
    ui_Level_3 = NULL;
    ui_WiFi3 = NULL;
    ui_Bluetooth3 = NULL;

}
