// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Fv1.0.0

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_defaultpage;
extern lv_obj_t * ui_TimeLable;
extern lv_obj_t * ui_TimerFunction;
extern lv_obj_t * ui_Locked;
extern lv_obj_t * ui_Level_70;
extern lv_obj_t * ui_WiFi;
extern lv_obj_t * ui_Bluetooth;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

