// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Fv1.0.0

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_TimeLable4 = NULL;
lv_obj_t * ui_TimerFunction4 = NULL;
lv_obj_t * ui_Locked4 = NULL;
lv_obj_t * ui_Level_4 = NULL;
lv_obj_t * ui_WiFi4 = NULL;
lv_obj_t * ui_Bluetooth4 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_titilestate_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 85
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 444
    lv_obj_set_x(ui_Image1, 20);
    lv_obj_set_y(ui_Image1, 20);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image14, &ui_img_cleandeepclean_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 189
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 440
    lv_obj_set_x(ui_Image14, 115);
    lv_obj_set_y(ui_Image14, 20);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image16, &ui_img_cleanquickclean_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 189
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 440
    lv_obj_set_x(ui_Image16, 115);
    lv_obj_set_y(ui_Image16, 20);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimeLable4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TimeLable4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLable4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLable4, -65);
    lv_obj_set_y(ui_TimeLable4, 235);
    lv_obj_set_align(ui_TimeLable4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLable4, "10:30 AM");
    lv_obj_set_style_transform_pivot_x(ui_TimeLable4, lv_obj_get_width(ui_TimeLable4) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_TimeLable4, lv_obj_get_height(ui_TimeLable4) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_TimeLable4, 2700, LV_PART_MAIN);

    ui_TimerFunction4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TimerFunction4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimerFunction4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimerFunction4, -65);
    lv_obj_set_y(ui_TimerFunction4, 155);
    lv_obj_set_align(ui_TimerFunction4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimerFunction4, "00:45:00");
    lv_obj_set_style_transform_pivot_x(ui_TimerFunction4, lv_obj_get_width(ui_TimerFunction4) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_TimerFunction4, lv_obj_get_height(ui_TimerFunction4) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_TimerFunction4, 2700, LV_PART_MAIN);

    ui_Locked4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Locked4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Locked4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Locked4, -68);
    lv_obj_set_y(ui_Locked4, 75);
    lv_obj_set_align(ui_Locked4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Locked4, "Locked");
    lv_obj_set_style_transform_pivot_x(ui_Locked4, lv_obj_get_width(ui_Locked4) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_Locked4, lv_obj_get_height(ui_Locked4) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_Locked4, 2700, LV_PART_MAIN);

    ui_Level_4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Level_4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Level_4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Level_4, -60);
    lv_obj_set_y(ui_Level_4, 2);
    lv_obj_set_align(ui_Level_4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Level_4, "Level 70%");
    lv_obj_set_style_transform_pivot_x(ui_Level_4, lv_obj_get_width(ui_Level_4) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_Level_4, lv_obj_get_height(ui_Level_4) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_Level_4, 2700, LV_PART_MAIN);

    ui_WiFi4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_WiFi4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFi4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFi4, -80);
    lv_obj_set_y(ui_WiFi4, -90);
    lv_obj_set_align(ui_WiFi4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFi4, "WiFi");
    lv_obj_set_style_transform_pivot_x(ui_WiFi4, lv_obj_get_width(ui_WiFi4) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_WiFi4, lv_obj_get_height(ui_WiFi4) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_WiFi4, 2700, LV_PART_MAIN);
    


    ui_Bluetooth4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Bluetooth4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Bluetooth4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Bluetooth4, -60);
    lv_obj_set_y(ui_Bluetooth4, -150);
    lv_obj_set_align(ui_Bluetooth4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Bluetooth4, "Bluetooth");
    lv_obj_set_style_transform_pivot_x(ui_Bluetooth4, lv_obj_get_width(ui_Bluetooth4) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_pivot_y(ui_Bluetooth4, lv_obj_get_height(ui_Bluetooth4) / 2, LV_PART_MAIN);
    lv_obj_set_style_transform_angle(ui_Bluetooth4, 2700, LV_PART_MAIN);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image1 = NULL;
    ui_Image14 = NULL;
    ui_Image16 = NULL;
    ui_TimeLable4 = NULL;
    ui_TimerFunction4 = NULL;
    ui_Locked4 = NULL;
    ui_Level_4 = NULL;
    ui_WiFi4 = NULL;
    ui_Bluetooth4 = NULL;

}
