// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Fv1.0.0

#ifndef _FV1_0_0_UI_H
#define _FV1_0_0_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"
#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_titilestate_png);    // assets/titilestate.png
LV_IMG_DECLARE(ui_img_homepage_png);    // assets/homepage.png
LV_IMG_DECLARE(ui_img_modeplantmilk_png);    // assets/modeplantmilk.png
LV_IMG_DECLARE(ui_img_menuclean_png);    // assets/menuclean.png
LV_IMG_DECLARE(ui_img_menutoufu_png);    // assets/menutoufu.png
LV_IMG_DECLARE(ui_img_process_png);    // assets/process.png
LV_IMG_DECLARE(ui_img_line_4_png);    // assets/Line 4.png
LV_IMG_DECLARE(ui_img_plantmilk_png);    // assets/plantmilk.png
LV_IMG_DECLARE(ui_img_tofu_png);    // assets/tofu.png
LV_IMG_DECLARE(ui_img_493133332);    // assets/clean-rotated.png
LV_IMG_DECLARE(ui_img_cleandeepclean_png);    // assets/cleandeepclean.png
LV_IMG_DECLARE(ui_img_cleanquickclean_png);    // assets/cleanquickclean.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
